//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfService.Data.Subscription))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfService.Data.User[]))]
    public partial class User : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private object[] SubscriptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Subscriptions
        {
            get
            {
                return this.SubscriptionsField;
            }
            set
            {
                this.SubscriptionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subscription", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Data")]
    public partial class Subscription : object
    {
        
        private int CallminutesField;
        
        private System.Guid IdField;
        
        private decimal PriceField;
        
        private decimal PriceIncVatAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Callminutes
        {
            get
            {
                return this.CallminutesField;
            }
            set
            {
                this.CallminutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceIncVatAmount
        {
            get
            {
                return this.PriceIncVatAmountField;
            }
            set
            {
                this.PriceIncVatAmountField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:11012/services/user", ConfigurationName="IUserService")]
public interface IUserService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/Add", ReplyAction="http://localhost:11012/services/user/IUserService/AddResponse")]
    System.Threading.Tasks.Task<WcfService.Data.User> AddAsync(WcfService.Data.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/AddSubscription", ReplyAction="http://localhost:11012/services/user/IUserService/AddSubscriptionResponse")]
    System.Threading.Tasks.Task<bool> AddSubscriptionAsync(WcfService.Data.User user, WcfService.Data.Subscription subscription);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/Delete", ReplyAction="http://localhost:11012/services/user/IUserService/DeleteResponse")]
    System.Threading.Tasks.Task<bool> DeleteAsync(WcfService.Data.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/Get", ReplyAction="http://localhost:11012/services/user/IUserService/GetResponse")]
    System.Threading.Tasks.Task<WcfService.Data.User> GetAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/GetAll", ReplyAction="http://localhost:11012/services/user/IUserService/GetAllResponse")]
    System.Threading.Tasks.Task<WcfService.Data.User[]> GetAllAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:11012/services/user/IUserService/Update", ReplyAction="http://localhost:11012/services/user/IUserService/UpdateResponse")]
    System.Threading.Tasks.Task<bool> UpdateAsync(WcfService.Data.User entity);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
public interface IUserServiceChannel : IUserService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
public partial class UserServiceClient : System.ServiceModel.ClientBase<IUserService>, IUserService
{
    
    public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<WcfService.Data.User> AddAsync(WcfService.Data.User entity)
    {
        return base.Channel.AddAsync(entity);
    }
    
    public System.Threading.Tasks.Task<bool> AddSubscriptionAsync(WcfService.Data.User user, WcfService.Data.Subscription subscription)
    {
        return base.Channel.AddSubscriptionAsync(user, subscription);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteAsync(WcfService.Data.User entity)
    {
        return base.Channel.DeleteAsync(entity);
    }
    
    public System.Threading.Tasks.Task<WcfService.Data.User> GetAsync(string id)
    {
        return base.Channel.GetAsync(id);
    }
    
    public System.Threading.Tasks.Task<WcfService.Data.User[]> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
    
    public System.Threading.Tasks.Task<bool> UpdateAsync(WcfService.Data.User entity)
    {
        return base.Channel.UpdateAsync(entity);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
}
